Closes #141
Backbase/variants pull request #170
Opened 2022-04-22 13:32 UTC by gderaco

### What does this PR do

### How can it be tested
Tell us how to test these changes

### Task
resolves #X (where `#X` is the number of an issue)

### Checklist:

- [ ] I ran `make validation` locally with success
- [ ] I have not introduced new bugs
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new errors

2022-04-22 13:35 UTC, obackbase commented
<!--
  0 failure: 
  1 warning:  Pull request is r...
  
  
  DangerID: danger-id-Danger;
-->


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>Pull request is relatively big. If this PR contains multiple changes,
consider splitting it into separate PRs for easier reviews.</td>
    </tr>
  </tbody>
</table>



<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/swift">Danger Swift</a> against b3158b8bf7be3638996f65d298b1dae7a1f41667
</p>

2022-04-28 15:38 UTC, GMinucci requested changes

2022-04-28 15:38 UTC, GMinucci commented on Sources/VariantsCore/Extensions/KeyedDecodingContainer+EnvVar.swift
> +    public func decode(_ type: String.Type, forKey key: KeyedDecodingContainer<K>.Key, extractEnvVar: Bool) throws -> String {
What about instead of the flag making the method itself more readable? Note that this one depends on my comment on the `extractEnvVarIfAny` method.
```swift
func decodeOrReadFromEnv(_ type: String.Type, forKey key: KeyedDecodingContainer<K>.Key) throws -> String {
    let decodedValue = try decode(String.self, forKey: key)
    return decodedValue.asEnvVariable ?? decodedValue
}
```

2022-04-28 15:38 UTC, GMinucci commented on Sources/VariantsCore/Extensions/KeyedDecodingContainer+EnvVar.swift
> +    public func decodeIfPresent(_ type: String.Type, forKey key: KeyedDecodingContainer<K>.Key, extractEnvVar: Bool) throws -> String? {
Same as above
```swift
func decodeIfPresentOrReadFromEnv(_ type: String.Type, forKey key: KeyedDecodingContainer<K>.Key) throws -> String {
    guard let decodedValue = try decodeIfPresent(String.self, forKey: key) else { return nil }
    return decodedValue.asEnvVariable ?? decodedValue
}
```

2022-04-28 15:38 UTC, GMinucci commented on Sources/VariantsCore/Extensions/String+EnvVar.swift
> +    func extractEnvVarIfAny() -> String {
This method is very tied to the logic present in `KeyedDecodingContainer+EnvVar`, if we leave as a global extension it can cause confusion or misuse. Can we move it to the file were it's being used and make it `fileprivate`?

2022-04-28 15:38 UTC, GMinucci commented on Sources/VariantsCore/Extensions/String+EnvVar.swift
> +    func extractEnvVarIfAny() -> String {
This can be called `asEnvVariable` to make it more readable. Then optionally return its result. If it's an env variable return its value, otherwise `nil`

2022-04-28 15:38 UTC, GMinucci commented on Sources/VariantsCore/Extensions/String+EnvVar.swift
> +        return self
If we make it return `nil` if not an env variable this can be simplified to
```suggestion
guard 
    let regexMatch = regex?.firstMatch(in: self, range: NSRange(location: 0, length: self.count)),
    let envVarName = Range(regexMatch.range(withName: "name"), in: self),
    let envVarRawValue = getenv(String(self[envVarName]))
else { return nil }
return String(utf8String: envVarRawValue)
```

2022-04-29 16:00 UTC, gderaco commented on Sources/VariantsCore/Extensions/KeyedDecodingContainer+EnvVar.swift
> +        let decodedValue = try self.decode(Int.self, forKey: key)
fixed and unit-tested

2022-04-29 17:37 UTC, obackbase approved these changes

2022-05-02 13:22 UTC, GMinucci requested changes

2022-05-02 13:22 UTC, GMinucci commented on Sources/VariantsCore/Extensions/KeyedDecodingContainer+EnvVar.swift
> +        return decoded
I'm not sure about having `0` as default in case some of the decoding fails. If we do this we could potentially be hiding possible failures in the config or env properties.
This could be written as
```swift
if let valueFromEnv = try? Int(decodeOrReadFromEnv(String.self, forKey: key)) {
    return valueFromEnv
else {
    return try decode(Int.self, forKey: key)
}
```

2022-05-02 13:27 UTC, GMinucci commented on Sources/VariantsCore/Extensions/KeyedDecodingContainer+EnvVar.swift
> +        return decoded
For example if we set `${{ envVars.V_VERSION }}` in the config file and there is no `V_VERSION` in the env properties it will set as `0` and no error will be thrown.
Following this line of thinking, should we raise an error in case user sets a property to be read from env properties and the property doesn't exist?

2022-05-03 07:13 UTC, GMinucci approved these changes

2022-05-03 09:04 UTC, obackbase approved these changes

2022-05-03 09:23 UTC, merged