#136 Variants list command
Backbase/variants pull request #171
Opened 2022-04-22 15:19 UTC by obackbase

### What does this PR do
New command `$ variants list` introduced, that shows all available variants

### How can it be tested
Tell us how to test these changes

### Task
resolves #136 

### Checklist:

- [ ] I ran `make validation` locally with success
- [ ] I have not introduced new bugs
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new errors

2022-04-29 16:13 UTC, gderaco commented
@obackbase  I run the command and there's a lot of space between the executed command and the output

2022-04-29 16:23 UTC, gderaco requested changes

2022-04-29 16:23 UTC, gderaco commented on Sources/VariantsCore/Commands/List.swift
> +//  Created by Oleg Baidalka on 31.03.2022.
please use the same headers as on the other files

2022-04-29 16:23 UTC, gderaco commented on Sources/VariantsCore/Schemas/Variant.swift
> +//  Created by Oleg Baidalka on 31.03.2022.
please use the same headers as on the other files

2022-04-29 16:23 UTC, gderaco commented on Tests/VariantsCoreTests/CommandTests.swift
> +//  Created by Oleg Baidalka on 29.04.2022.
please use the same headers as on the other files

2022-04-29 17:32 UTC, obackbase commented on Sources/VariantsCore/Commands/List.swift
> +//  Created by Oleg Baidalka on 31.03.2022.
like what? It is like other files

2022-04-29 17:34 UTC, obackbase commented
> @obackbase I run the command and there's a lot of space between the executed command and the output

this was made with the purpose to keep the space for the selected variant. Once `isCurrent(Variant)` function implemented correctly it will print with `* ` to highlight current variant (same as in `git branch`)

2022-05-02 09:03 UTC, gderaco commented on Sources/VariantsCore/Commands/List.swift
> +//  Created by Oleg Baidalka on 31.03.2022.
the date should not be there

2022-05-02 09:46 UTC, obackbase commented on Sources/VariantsCore/Commands/List.swift
> +//  Created by Oleg Baidalka on 31.03.2022.
ah. ok

2022-05-02 11:20 UTC, gderaco approved these changes
LGTM

2022-05-02 12:52 UTC, GMinucci commented on Sources/VariantsCore/Commands/List.swift
> +extension Variant {
Should this be a `fileprivate` extension? If not then can we move it to a separate file?

2022-05-02 14:45 UTC, obackbase commented on Sources/VariantsCore/Commands/List.swift
> +extension Variant {
was before `fileprivate` but can't tests are firing errors, so I remove that
> VerboseLoggerTests.swift:57:32: 'print' is inaccessible due to 'fileprivate' protection level

2022-05-02 14:49 UTC, GMinucci approved these changes

2022-05-02 14:54 UTC, merged