feature: Expose configuration variables key to Variants.swift
Backbase/variants pull request #201
Opened 2022-12-07 12:35 UTC by romanhu-bb

### What does this PR do
-Based on `variants.yml` generate in `Variants.swift` if needed enum `ConfigurationValueKey` with configuration variable's names as keys. Now, to read configuration value you can use next code: 
 ```swift Variants.configurationValue(key: .A_PROPERTY)```

While old way is kept as well
```swift Variants.configuration["A_PROPERTY"]```

### How can it be tested
Add into yml custom not environment properties with destination project and try command `variants setup`. In generated 'Variants.swift' you should found all properties as enum cases

### Task
resolves #125  (where `#X` is the number of an issue)

### Checklist:

- [x ] I ran `make validation` locally with success
- [x ] I have not introduced new bugs
- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [x ] I have commented on my code, particularly in hard-to-understand areas
- [x ] I have made corresponding changes to the documentation
- [x ] My changes generate no new errors

2022-12-08 08:42 UTC, arthurpalves requested changes
Great job @romanhu-bb! There are only a few things to be polished

2022-12-08 08:42 UTC, arthurpalves commented on Sources/VariantsCore/Factory/iOS/VariantsFileFactory.swift
>      /// encrypted static variables
`encrypted` only applies to `Variants.Secrets`

2022-12-08 08:42 UTC, arthurpalves commented on Templates/ios/Variants.swift.template.gyb
> +    {% if variables %}
When creating the context in `VariantsFileFactory` you named these `configurationValues` and not `variables`, so it will always be empty.

2022-12-08 08:42 UTC, arthurpalves commented on Templates/ios/Variants.swift.template.gyb
> +    /// Environment variables coming from variants.yml as enum values
They aren't environment variables though, needs a better name and description

2022-12-08 08:42 UTC, arthurpalves commented on Templates/ios/Variants.swift.template.gyb
> +    }
Here you don't need to specify the "raw" value, as it's the same as the key:
```
    public enum EnvironmentVariableKey: String { {% for envVar in variables %}
        case {{ envVar.name }} {% endfor %}
    }
```

Other than finding a more suitable name for the enum, as pointed above they don't represent environment variables.

2022-12-08 08:42 UTC, arthurpalves commented on Templates/ios/Variants.swift.template.gyb
> +    static func configurationValue(for key:EnvironmentVariableKey) -> Any? {
```suggestion
    static func configurationValue(for key: EnvironmentVariableKey) -> Any? {
```

2022-12-08 08:42 UTC, arthurpalves commented on Templates/ios/Variants.swift.template.gyb
> +    /// Environment variables coming from variants.yml as enum values
Checking further changes, I believe you meant this to be `ConfigurationValueKey`?

2022-12-08 08:42 UTC, arthurpalves commented on docs/ENVIRONMENT_VARIABLES.md
> +    }
```suggestion
    public enum ConfigurationValueKey: String { 
        case A_PROPERTY
    }
```

2022-12-08 08:42 UTC, arthurpalves commented on docs/ENVIRONMENT_VARIABLES.md
> +Variants.configurationValue(key: .A_PROPERTY)
```suggestion
Variants.configurationValue(for: .A_PROPERTY)
```

2022-12-08 15:07 UTC, romanhu-bb commented on Sources/VariantsCore/Factory/iOS/VariantsFileFactory.swift
>      /// encrypted static variables
Fixed

2022-12-14 14:16 UTC, arthurpalves approved these changes
Awesome. Thanks for the changes!

2022-12-14 15:58 UTC, merged