Add PostSwitchScript to iOSConfiguration and to iOSVariant
Backbase/variants pull request #223
Opened 2023-05-15 08:45 UTC by noursandidb

### What does this PR do
- in this PR, post switch script is added, so whenever a user wants to run a specific script after switching variants, they can either do that for a specific variant, or for global switching, or for both
- if the user specifies both variant specific and global postSwitchScript, we will run the variants specific one first and then the global one

### How can it be tested
add a postSwitchScript to your variants.yml and it will be executed
- Add one postSwitchScript in a variant
- Add another one on the global layer of the yaml file
- Remove both to make sure that it's optional

### Task
resolves #X (where `#X` is the number of an issue)

### Checklist:

- [x] I ran `make validation` locally with success
- [x] I have not introduced new bugs
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new errors

2023-05-31 10:06 UTC, GMinucci reviewed
One note about the naming here: `postSwitchScript` for me implies you are providing a script to be run. In the case of the example here you are providing commands directly instead.
It will also work if you simply provide the path to an executable bash file but it would be nice to mention it in the documentation somewhere that we have both capabilities.

2023-09-21 10:09 UTC, AlexKuzyaev commented on Sources/VariantsCore/Custom Types/Project/iOSProject.swift
> +        guard let outputString = try Bash("bash", arguments: "-c", script).capture() else { return }
This is true, `"-c"` is added automatically inside `.capture()`. 
But for some reason if I remove `"-c"` from this line, I receive this error: `/bin/bash: : No such file or directory` and script is not working.

I don't have a lot of experience with Bash, and I was not able to find a solution so far. 
@GMinucci do you know what might be the reason?

2023-09-26 10:05 UTC, GMinucci requested changes

2023-09-26 10:05 UTC, GMinucci commented on docs/ios/POST_SWITCH_SCRIPT.md
> +- **Multi-Line Commands**: Starting with |- is mandatory if you have multi-line commands or want to start a command on a new line for readability.
Starting with `|-` is not bash scripting related but a yaml specification. Additionally, we should use `>-` instead of `|-` here to strip the last `\n`

2023-09-26 10:05 UTC, GMinucci commented on docs/ios/POST_SWITCH_SCRIPT.md
> +Here are some additional details for users who may not be familiar with bash scripting:
We can omit this line to make this more generic
```suggestion
```

2023-09-26 10:05 UTC, GMinucci commented on Sources/VariantsCore/Custom Types/Project/iOSProject.swift
> +        guard let outputString = try Bash("bash", arguments: "-c", script).capture() else { return }
I'm not sure, could be an issue in the library. I need to further investigate but it should be harmless to keep the `-c`

2023-09-26 14:10 UTC, AlexKuzyaev commented on Sources/VariantsCore/Schemas/iOS/iOSVariant.swift
> +// swiftlint:enable line_length
I see this warning from `swiftlint` when I remove these lines at the end of files

`/variants/Tests/VariantsTests/InitCommandTests.swift:11:22: warning: Blanket Disable Command Violation: The disabled 'line_length' rule should be re-enabled before the end of the file (blanket_disable_command)`

2023-09-28 07:12 UTC, GMinucci commented on Sources/VariantsCore/Schemas/iOS/iOSVariant.swift
> +// swiftlint:enable line_length
Interesting, I'll check later why is that. Thanks for the heads up!

2023-09-28 07:13 UTC, GMinucci approved these changes

2023-09-28 07:22 UTC, arthurpalves requested changes
Technically ready, just 2 minor comments related to the docs.

2023-09-28 07:22 UTC, arthurpalves commented on docs/ios/POST_SWITCH_SCRIPT.md
> +The "Post Switch Script" feature is optional for both local and global. In case you want to not use it you can simply omit the configuration in the `variants.yml` file.
> In case you want to not use it

- [ ] This should be rephrased as:

> In case you don't want to use it.

2023-09-28 07:22 UTC, arthurpalves commented on docs/ios/POST_SWITCH_SCRIPT.md
> +      ```yaml
Indentation is wrong, does this render correctly?

2023-09-28 11:09 UTC, AlexKuzyaev commented on docs/ios/POST_SWITCH_SCRIPT.md
> +      ```yaml
Thank you, I updated the documentation 👍

2023-09-28 11:28 UTC, arthurpalves approved these changes

2023-09-28 14:32 UTC, merged