Docs/configuring android
Backbase/variants pull request #98
Opened 2020-11-23 17:51 UTC by BBWillNasby

### What does this PR do
- Adds documentation on configuring an Android project, and documentation on deploying with appcenter while using AND not using github secrets.

### How can it be tested
No testing needed.

### Task

### Checklist:

- [ ] I ran `make validation` locally with success
- [ ] I have not introduced new bugs
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new errors

2020-11-24 08:58 UTC, arthurpalves requested changes
Thanks Will!
Just a few adjustments needed. 👍🏽

2020-11-24 08:58 UTC, arthurpalves commented on docs/APPCENTER.md
> +## Deploying with AppCenter
Can I suggest `Deploying to AppCenter`?

2020-11-24 08:58 UTC, arthurpalves commented on docs/APPCENTER.md
> +Fastlane can be configured to make deployments to AppCenter with a single command. There are only a few requirements for this.
I think we could be a bit more descriptive here. In the lines of
```
The fastlane setup you get, out of this tool, when running `variants setup` includes the ability to deploy your mobile app to multiple stores (link this to the store destination doc). Deploying to AppCenter can be achieved solely by making changes to your `variants.yml` spec.

This doesn't, however, create the application on AppCenter for you. You're required to have an AppCenter account (from which you'll generate an API token) and have created an application in AppCenter beforehand.
```

2020-11-24 08:58 UTC, arthurpalves commented on docs/APPCENTER.md
> +### Getting Started
In my opinion it should be clear that this part is outside of this tools' responsibility and also a one time task. Perhaps renaming it to `### What you should do beforehand` would achieve this?

2020-11-24 08:58 UTC, arthurpalves commented on docs/APPCENTER.md
> +
I feel we're missing one section for `### Setting up environment variables`, pointing to the `appcenter_params.rb` (explaining how that params file is used). Where it's clear to the developer that the values recorded in the section above (1. owner name, 2. API token) should be set as env vars `APPCENTER_OWNER_NAME` and `APPCENTER_API_TOKEN`. There is also the option `APPCENTER_DESTINATION_GROUP` that fallbacks to `Collaborators`, which should be explained.

I think `APPCENTER_APP_NAME` should receive its own section after this as well. So that we explain properly why this is the only value that comes from `variants[#].custom` and that it should match the name recorded in the prior section.

This already ensures that deploying to AppCenter works, most importantly on a developer's machine. While the next section `### Deploying to AppCenter using GitHub Secrets` dives into an opinionated CI integration with Github Actions.

2020-11-24 08:58 UTC, arthurpalves commented on docs/APPCENTER.md
> +1. Add a custom value to the specific variant you're making the deployment for, inside your `variants.yml`
This could be part of its own section regarding `APPCENTER_APP_NAME`, that makes more sense imo - as stated above. This section should then be focused only on setting environment variables whose values come from Github secrets. Also, having the secrets in place don't make them available as environment variables, this is [something that should be set](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#environment-files), you can see more here (can also reference this official doc after a brief explanation)

2020-11-24 08:58 UTC, arthurpalves commented on docs/CONFIGURING_ANDROID.md
> +If `variants init` has been run successfully, you will see a `variants.yml` file in your project directory. This is where we configure the variants for our project.
I think it's valid if we have a `Contents` section here to start with. Some people might be looking for something specific that is further down.

Something like this:
![Screenshot 2020-11-24 at 09 52 25](https://user-images.githubusercontent.com/1584586/100070912-c4394300-2e3a-11eb-9ec9-ef129aecf065.png)

2020-11-24 08:58 UTC, arthurpalves commented on docs/CONFIGURING_ANDROID.md
> +First, it is important to note that the values from the configuration will be placed in multiple locations. For example, values for fastlane are stored in `./fastlane/parameters`, while gradle values
> set with the `destination` value

Could you reference the docs for it?

> since we already know where those values should be used

Using `Since Variants know` could make more sense?

2020-11-24 08:58 UTC, arthurpalves commented on docs/CONFIGURING_ANDROID.md
> +### Configuring project
Perhaps include this section and the ones below under a bigger `## Working with variants.yml`?

2020-11-24 08:58 UTC, arthurpalves commented on docs/CONFIGURING_ANDROID.md
> +### Configuring variants
We could just specify here that a variant named `default` is mandatory and regularly used as _production_ variant?

2020-11-24 08:58 UTC, arthurpalves commented on docs/CONFIGURING_ANDROID.md
> +- `name`: The name to reference the variant. This is namely used to select which variant to use via the switch command. Ex: `variant switch —platform android —variant test`.
There should be double dash on the command line options, i.e. `--variant` instead of `-variant`.
Also, perhaps we should remove `--platform android` since auto platform detection happens most of the time.

2020-11-24 08:58 UTC, arthurpalves commented on docs/CONFIGURING_ANDROID.md
> +- `store_destination`: The destination for your build. Currently there are only two options, `PlayStore` and `AppCenter`. More information can be found in the `STORE_DESTINATION` documentation.
> in the `STORE_DESTINATION` documentation.

Can we link to that doc? i.e.: 
```
in the [STORE_DESTINATION documentation](../STORE_DESTINATION.md)
```

2020-11-24 08:58 UTC, arthurpalves commented on docs/CONFIGURING_ANDROID.md
> +Each variant can also have custom values if your needs were not met by the standard values. More information on these can be found in the `CUSTOM_PROPERTY` documentation. A common example of this is
> in the `CUSTOM_PROPERTY` documentation.

Again, can we link to the doc?

2020-11-24 08:58 UTC, arthurpalves commented on docs/CONFIGURING_ANDROID.md
> +Once your project has been configured, you can setup the project with `variants setup`. Note that this generates files for your default variant. If you wish to setup a project for a non-default varia
> Once your project has been configured

The project will be configured as an outcome of all these tasks. Perhaps this should be rephrased to something like `"Once your variants.yml spec has been configured"`?

> If you wish to setup a project for a non-default variant, first run the setup command `variants setup`

This might give the idea that I need to run `variants setup` first every time I want to run `switch`. We should perhaps state that `setup` is usually used once for a project, once it's done we should rely on 1. making changes to `variants.yml` and 2. running `variants switch`, as switch will also update `variants.gradle` and files in `fastlane/parameters/*`. It won't, however, generate the `fastlane/` setup for you in case you've skipped it when running `variants setup` in the first place.

> More information on commands can be found in the project README

Can you also link to README?

2020-12-17 20:51 UTC, BBWillNasby commented on docs/APPCENTER.md
> +Fastlane can be configured to make deployments to AppCenter with a single command. There are only a few requirements for this.
I made changes here. I didn't include the information about requiring an AppCenter account, app creation, and API token because all of this is covered directly below in "getting starting"

2020-12-17 20:58 UTC, BBWillNasby commented on docs/APPCENTER.md
> +### Getting Started
I changed it to "preparation" for simplicity sake.

2020-12-18 11:53 UTC, arthurpalves approved these changes

2020-12-18 11:53 UTC, merged